apiVersion: v1
kind: ConfigMap
metadata:
  name: event-exporter-cfg
  namespace: monitoring
data:
  config.yaml: |
    logLevel: info
    logFormat: pretty
    metricsNamePrefix: event_exporter_
    route:
      routes:
        - match:
            - receiver: "dump"
    receivers:
      - name: "dump"
        stdout:
          layout:
            message: "{{ .Message }}"